export const stacks = [
    {
        title: "Front End",
        text: "The client side of the website, what the is greeted by and interacts with. The combination of the graphic design and user interface.",
        iconOne: "./img/icons/javascript.svg",
        iconOneText: "Javascript",
        iconTwo: "./img/icons/react.svg",
        iconTwoText: "React",
        iconThree: "./img/icons/bootstrap.svg",
        iconThreeText: "Bootstrap",
    },
    {
        title: "Back End",
        text: "The server side of the website, what does all the processing for requests from the client side. responsible for storing and organizing data, and ensuring everything on the client-side actually works",
        iconOne: "./img/icons/python.svg",
        iconOneText: "Python",
        iconTwo: "./img/icons/postgresql.svg",
        iconTwoText: "PostgreSQL",
        iconThree: "./img/icons/django.svg",
        iconThreeText: "Django",
    },
    {
        title: "Tools",
        text: "Not a necessity but you can't go wrong with increased workflow and efficiency, and these are how I get to that increase.",
        iconOne: "./img/icons/github.svg",
        iconOneText: "Github",
        iconTwo: "./img/icons/google.svg",
        iconTwoText: "Google",
        iconThree: "./img/icons/slack.svg",
        iconThreeText: "Slack",
    },
]

export const projects = [
    {
        title: "Marketopia Frontend",
        id: "marketopiafront",
        img: "./img/project-teasers/marketopia-teaser.png",
        imgAlt: "Marketopia teaser",
        modal: "This was the capstone project for the Awesome Inc bootcamp, finally combining all the skills from frontend and backend!, I made a marketplace-clone and built the front end with Nextjs, and tailwindCSS. Users can post any listing they please, others users can use a range of filters to find that perfect listing, then message the other user, and leave a review if they had a good experience with that user.",
        projectLink: "https://marketopia-frontend.vercel.app/",
        githubLink: "https://github.com/ZacRayTho/Marketopia-Frontend"
    },
    {
        title: "Marketopia Backend",
        id: "marketopiaback",
        img: "./img/project-teasers/marketopia-teaser.png",
        imgAlt: "Marketopia teaser",
        modal: "This was the capstone project for the Awesome Inc bootcamp, finally combining all the skills from frontend and backend! I made the backend with Django REST API, and Postgres. , I constructed a powerful backend that efficiently manages the data, implements complex relationships, and provides specific views to retrieve filtered and queried results.",
        projectLink: "https://marketopia-frontend.vercel.app/",
        githubLink: "https://github.com/ZacRayTho/Marketopia-Backend"
    },
    {
        title: "Marketopia MVP",
        id: "marketopiamvp",
        img: "./img/project-teasers/marketopia-mvp.png",
        imgAlt: "Marketopia docs",
        modal: "Before starting the capstone project, we took an entire week to think through the entire website, database and more! We had to think through our project's MoSCoW, through multiple user personas. We then built off the user personas into as many stories that we could think through. After getting the sign off on the MVP , We also had to make a Kanban board from the multiple user stories and MoSCoW. Checkout the Kanban board through the repo link!",
        projectLink: "https://docs.google.com/document/d/11c9QjbHW8q9YvY5ASa26yfVi5JBEQpvP9e01MZ7ZZKc/edit?usp=sharing",
        githubLink: "https://github.com/users/ZacRayTho/projects/1"
    },
    {
        title: "Twitter Clone",
        id: "twitter",
        img: "./img/project-teasers/twitter-teaser.png",
        imgAlt: "Teaser Clone",
        modal: "I created a Twitter clone while we moved to backend development. This project allowed me to experiment with Next.js, Tailwind CSS, and Typescript while keeping my React and JavaScript skills up-to-date. The application is designed to mimic the functionality and user experience of Twitter, with features like login with NextAuth through twitter's API, posting, and commenting.",
        projectLink: "https://twitter-clone-rho-two.vercel.app/",
        githubLink: "https://github.com/ZacRayTho/twitter-clone"
    },
    {
        title: "Weather app",
        id: "weatherapp",
        img: "./img/project-teasers/weather-app-teaser.png",
        imgAlt: "Teaser of Weather App",
        modal: "Our first time using axios and pulling data from an outside source AKA an API. This is a rather simple app, simply displaying the temp of whatever zip code you put in,or if you allow it, can use your browsers geolocation to find your zip out automatically. As an extra challenge, we had to generate html elements using javascript.",
        projectLink: "https://zacraytho.github.io/weather-app/",
        githubLink: "https://github.com/ZacRayTho/weather-app"
    },
    {
        title: "Tic-Tac-Toe",
        id: "tictactoe",
        img: "./img/project-teasers/tic-tac-toe-teaser.png",
        imgAlt: "Teaser of Tic Tac Toe",
        modal: "Our second big project, maybe not super advanced for a human, but getting the human logic into code that the computer will understand was the real challenge of this project. It really made me stop and think and pseudocode before hopping straight into coding, sadly I still had a couple hiccups along the way because of bad logic on my part.",
        projectLink: "https://zacraytho.github.io/tic-tac-toe/",
        githubLink: "https://github.com/ZacRayTho/tic-tac-toe"
    },
    {
        title: "To-Do List",
        id: "todolist",
        img: "./img/project-teasers/to-do-list-teaser.png",
        imgAlt: "Teaser of To Do List",
        modal: "Our first project after React's introduction, meant for us to get use to it's form of state and the way it renders HTML elements as components in Javascript. Definitely the hardest project up to this point, but i'll probably say that every coming week as we travel away from the VanillaJS which I had experience with prior to the bootcamp.",
        projectLink: "https://zacraytho.github.io/To-do-list/",
        githubLink: "https://github.com/ZacRayTho/To-do-list"
    },
    {
        title: "Restaurant Menu",
        id: "restaurant",
        img: "./img/project-teasers/restaurant-teaser.png",
        imgAlt: "Teaser of Restaurant Menu",
        modal: "Our Second project with React, this time we were tasked with pulling info from an API and displaying it with React components. This was a more open ended project, and definitely was harder to start because of that but after looking at a few real restaurant website I had my target in site. I really tried to replicate a functioning restaurant frontend.",
        projectLink: "https://zacraytho.github.io/react-restaurants/#/",
        githubLink: "https://github.com/ZacRayTho/react-restaurants"
    },
    {
        title: "Budget app",
        id: "Budget",
        img: "./img/python.png",
        imgAlt: "Python logo",
        modal: "During the first week of backend development in the bootcamp, We were tasked with writing a single class in Python and various methods to manipulate and interact with the Category class. To ensure the correctness of the implementation, I practiced Test Driven Development (TDD) and created a separate test file that contains assertions for each method.",
        projectLink: "https://github.com/ZacRayTho/budget_app",
        githubLink: "https://github.com/ZacRayTho/budget_app"
    },
    {
        title: "SQL Heroes",
        id: "sqlheroes",
        img: "./img/sql-logo.png",
        imgAlt: "SQL Logo",
        modal: "During the second week of backend development in the bootcamp, we worked with PostgreSQL and Python to create a terminal-based database from a set of provided tables about heroes. Using SQL commands and Python code, we created a schema for the database, populated it with data, and implemented various features such as searching, adding, and updating records.",
        projectLink: "https://github.com/ZacRayTho/sql-heroes",
        githubLink: "https://github.com/ZacRayTho/sql-heroes"
    },
    {
        title: "Django Heroes",
        id: "djangoheroes",
        img: "./img/django.png",
        imgAlt: "Django Logo",
        modal: "During the third week of backend development in the bootcamp, we delved into the world of web frameworks with Django. Building on our previous experience with SQL and Python, we were tasked with recreating our 'SQL Heroes' database in Django. To prepare for this project, I completed the Django documentation tutorial, which introduced me to the basics of Django's architecture, including models, and views.",
        projectLink: "https://github.com/ZacRayTho/sql-heroes-django",
        githubLink: "https://github.com/ZacRayTho/sql-heroes-django"
    },
    {
        title: "Django Jams",
        id: "djangojams",
        img: "./img/django.png",
        imgAlt: "Django Logo",
        modal: "This project was my introduction Django REST Framework. Using these tools, We created a music library backend with separate tables for artists, songs, genre, and more. Throughout the project, I learned about serializers, viewsets, and URLs, and tested everything using ThunderClient. With these tools at my belt, I could build my own API and this would wrap up the backend development section of the bootcamp.",
        projectLink: "https://github.com/ZacRayTho/django-jams-project",
        githubLink: "https://github.com/ZacRayTho/django-jams-project"
    },
    {
        title: "Coming soon",
        id: "Coming soon",
        img: "Coming soon",
        imgAlt: "Coming soon",
        modal: "Coming soon",
        projectLink: "Coming soon",
        githubLink: "Coming soon"
    },
    {
        title: "Coming soon",
        id: "Coming soon",
        img: "Coming soon",
        imgAlt: "Coming soon",
        modal: "Coming soon",
        projectLink: "Coming soon",
        githubLink: "Coming soon"
    }
]


export const blogs = [
    {
        header: "The First Week",
        date: "1-31-2023",
        img: "../img/contactStuff/github.svg",
        imgAlt: "Github Icon",
        first: "Week one wasn't what I expected, its been slower and not as code oriented as I would think. Although I admit, I didn't even know what a version control system was, but after git's introduction I can absolutely understand the importance of it. I would hate to have to manual revert a big chunk of code after I found out it was buggy or unusable. I also appreciate the slow intro into everything instead of jumping off on the deep end.",
        second: "I'm eager to learn more about coding, and just learn in general. I think learning is some of the most fun possible with the right subject, teacher, and environment. I would say that this bootcamp has all of that and more. Personally I can't wait to learn about all the different languages we're gonna use and about their ins and outs, and why some are better at certain tasks more than others.",
        third: "I get sporadic bursts of interests in things, like learning to solve a rubik's cube or flip a butterfly knife. But some interests don't stick so when I picked up coding as an interest and found this bootcamp, I was unsure if I would stick with it. That's why I took the Intro to Web course and did other various online courses for probably 6 months leading up to applying for the bootcamp.",
        id: 0,
    },
    {
        header: "Second Week of Onboarding",
        date: "2-6-2023",     img: "../img/html-css-js-logos.png",
        imgAlt: "HTML, CSS, and Javascript Logos",
        first: "HTML/CSS/JS each play an important role in the whole UX process. While we could write everything in pure HTML that wouldn't be a pleasant experience and I believe the internet would be a way less interesting place if every site looked and behaved exactly the same. No one wants to go a site that looks like its been around since the dawn of computers.",
        second: "I understand the importance of pseudocoding, its a high level interpretation of code that anyone should be able to read and understand. Its suppose to lay out the foundation for all the coding in the rest of the project. This helps work through the logic of the problems at hand thoroughly so when we start coding, we only need to worry about the syntax which will be super easy as we work more with each language.",
        third: "Onboarding remotely was definitely different from a traditional classroom setting because there was no teacher directly in front of me to ask questions to, and because I was on a computer anyways I felt more inclined to google my questions before reaching out in the help channel. Even though I didn't use The help channel this week, seeing other peoples having similar problems made me feel like I wasn't totally off the path that was laid out. Also seeing other peoples projects was nice, because I could get ideas from them and take pieces from their code to fix problems in mine.",
        id: 1,
    },
    {
        header: "HTML/CSS/State",
        date: "2-13-23",
        img: "../img/bootstrapLogo.png",
        imgAlt: "Bootstrap logo",
        first: "Bootstrap Has way more classes than i know what to do with , but oddly still is very limiting sometimes, so figuring out when its better to use bootstrap or normal CSS will help me a lot in the future. Bootstraps 'justify-content-center' and 'justify-content-center' are the most important for aligning stuff i'd argue and yet they're the most finicky,sometimes they don't work at all or don't work on children elements and I ended up having to repeat the class name on 3 elements within each other.",
        second: "Definitely would like to learn more bootstrap, so I can properly use it's classes to the fullest of their abilities. For Javascript,Nothing specific, but i'd love to learn more about all its function,methods, and capabilities so I can be the most proficient in my class.",
        third: "I worked at walmart for 4 years and didn't want to just work retail all my life,and management definitely isn't for me. I always wanted to have a more important job and make more money and tried my hand at several things but either didn't care for them or the pay at the end of the road wasn't worth it to me. Of course I also want to provide for my family as well, and be able to take care of them. But I'd say its mostly my want to better myself.",
        id: 2,
    },
    {
        header: "VanillaJS",
        date: "2-20-23",
        img: "../img/js-logo.png",
        imgAlt: "Javascript Logo",
        first: "You can't have everything right when you want it ,and you can't always expect to get back the results you want. thats how APIs work,you have to program accordingly so as not to hinder the User experience by waiting on the results of an API. You must program defensively incase the API doesn't return what you expected.",
        second: "What does it mean to develop good code? It means to develop code that gets the job done in the most simple way without hindering performance or user experience. Without unnecessary repeating variables or functions(DRY). It also means good documentation/pseudocode to back up your code so its easier to understand it after a extended period away from it or in the case that someone else has to interact with it.",
        third: "What does it mean to be a good developer? Good developers should code simply but efficiently to get the job done without extra unnecessary code. Developers should also think about all possible outcomes of their functions and about user interactions that may have a negative outcome on the code/site itself if not used appropriately. Most obviously to practice good coding practices and understand the end goal thoroughly before even beginning the code.", 
        id: 3,
        fourth: "What is one thing that programmers hate doing? Definitely typing/repeating themselves,theres so many ways to avoid writing extra code,wether it be a re usable function,an external library/framework that pulls in its own functions/methods that wave a wand and magically return what you asking for. Not to mention the tons of built in functions/methods that are included in javascript alone.",
    },
    {
        header: "Technical Article",
        date: "2-27-23",
        img: "../img/tip-iceberg.jpg",
        imgAlt: "Iceberg in Water",
        first: "The most basic definition of pseudocode to me, is a high level 'coding language'. A more in depth definition would be, pseudocode is every step that you want the computer to go through,broken down into the most basic logic, until you have identified everything needed for every step. Its writing out all possible functions you may need, and all variables that function may need or a variable that every function in the program needs access to. There are lots of ways to add to your pseudocode, so to help you think more in depth about everything.",
        second: "One of the first things we learned about was atomic design and how to identify parts of a webpage/wireframe and break them down into atoms, molecules, and organisms. We recently learned about MoSCoW which stands for 'Must Have,Should Have,Could Have, and Won't Have'. While I wouldn't say its pseudocode directly, it can help keep your direction while pseudocoding so you don't get hung up on a detail that you could have and focus more on what you must have. Theres also the 'User Journey' which describes the process the user go through when operating the app/website.",
        third: "Pseudocode helps programmers in the first half of the development process so you can work through the logic only without having to worry about syntax of the coding language. It also is more readable for a human so that a development team doesn't have to question each other about what they mean by some form of code. Best of all pseudocode can be translated into any programming language you want easily, given that you know that languages syntax already.",
        id: 4,
    },
    {
        header: "React Intro",
        date: "3-3-2023",
        img: "../img/react.png",
        imgAlt: "React Logo",
        first: "I think JavaScript Libraries at first are hard to use because they introduce new things and new ways to do things that were previously impossible. Having one week with React under my belt, I would say they aren't really hard to use. Its still Javascript, just with a some new syntax and built in functions",
        second: "In my self studies, I started learning about Flask, which seems very similar to React with using a single html 'boilerplate'/skeleton. I don't think we go over that in this bootcamp but I believe Django will be a better framework. I think Django is a more developed framework and Flask is meant to be more lightweight. Regardless i'm excited to learn more about React and Django when we get there.",
        third: "As I researched emerging Javascript tools, React seems to be the newest and most popular JavaScript tool out right now. I would like to learn about Angular as its a framework instead of library. From what i've read libraries are more in control of the workflow and Angular may get harder to debug as the project grows due to it changing the view and model based on each other. I still would think it would be fun and give me a different angle into web development.",
        id: 5,
    },
    {
        header: "CLI",
        date: "3-10-23",
        img: "../img/CLI.png",
        imgAlt: "Command line MS-DOS",
        first: "I've learned that CLI's are the original way people had to operate computers,before GUIs and mouses took over. I think to the uninformed they are, because you don't know what to say, what the computer can understand or what it expects from you. I would say after some time with them (learning Git commands and navigating files with just CLI), they aren't scary and they actually improve speed, because as you learn more commands and get more familiar with them, you have to take your hands away from the keyboard less. Navigating GUIs are inherently slower but more user friendly.",
        second: "If I were to build a CLI, it would probably just have more simple shortcuts for common things, like a shorthand that `git add .` `git commit` and `git push`. because each of those individually takes time. Or maybe add a command that starts an old text-adventure based RPG for some cognitive breaks.",
        third: "Creating a big website with multiple pages, like wikipedia. Having separate pages for each files also contains a ton of copy and pasted code which if 2 pages shared info retaining to would mean more hard code that would need to be found and then changed. Styling would also be way more involved without a framework like bootstrap, considering how deep CSS itself is, just trying to find something that Bootstrap doesn't make easy to use is a involved process.",
        id: 6,
    },
    {
        header: "Halfway!",
        date: "3-17-23",
        img: "../img/python.png",
        imgAlt: "Python Logo",
        first: "My biggest hurdle probably was stepping outside of VanillaJS, since thats where most of my prior experience was, I didn't even think about single page applications being a thing prior to React's introduction. I just assumed that every webpage had its own HTML file that a bunch a stuff of copied and pasted to each time. My next hurdle I think will be just back-end in general with no visuals to look at for immediate feedback on if something is working or not. I also definitely know the final project will be the biggest hurdle at the end of the road, as well as all the interviews I'll probably have to do before landing a career.",
        second: "A safe bet for a final project would probably be an Ebay/Marketplace or other popular site clone. I don't see anything wrong with my two previous ideas of, a car dealership website , or TCGplayer clone. Although I don't know if the car dealership site would use everything I'll learn by the end of the bootcamp, and thats one of the big reasons for the final project, to show off all your new skills and everything you know.",
        third: "I've had a little prior experience with python prior to the bootcamp, since it's what pops up most frequently when you google 'what coding language should I learn?'. But I mostly just learned syntax and didn't really do any projects myself, mostly watched videos. I know now that video may be a important part of the learning process, but if you never code yourself, it won't stick. It was different from JS because we already knew most of the correct general syntax and functions. Its weird certain methods in JS are their own function in python like len(str) instead of str.len . Hopping into (P)OOP immediately also was different, classes are something that I always knew were there but never really messed with. I can't wait to use them more next week and see how often we reuse them in the project.",
        id: 7,
    },
    {
        header: "Python",
        date: "3-24-23",
        img: "../img/sql-logo.png",
        imgAlt: "S Q L logo",
        first: "Theres a lot of similarities between JS and Python, they both have similar functions and abilities, both are pretty capable of the same stuff. Where they differ at is , Python is unable to access the DOM like JS can, and they both have there own syntax rules and formatting.",
        second: "Starting with python would have also meant starting with the backend, which I think may have been more difficult since the backend is more technical. Moving from Python to Javascript would have also been more difficult since python has much less syntax to remember besides the indentation. I like the Bootcamp's style of starting with something the hard way to get an understanding of whats happening, then introducing something else which makes it easier for us. ",
        third: "Thinking about all the websites I use in a daily basis, I definitely have a better understanding of how they work and even how some databases might be structured. I don't think I would enjoy building a big database and thinking of all the queries necessary to get only a little amount of data back. I understand the importance of databases and SQL, and could probably work in depth with them if needed but its not high on my list of wants.",
        id: 8,
    },
    {
        header: "Django",
        date: "4-7-23",
        img: "../img/django.png",
        imgAlt: "Django Logo",
        first: "I think it's pretty hard to narrow what i'm struggling with the most in the tech stack. Some times I struggle with aligning front end components, other times trying to get the specific data from queries can be a hassle. Django definitely helps with queries though and sometimes bootstrap cooperates and aligns stuff how I want.",
        second: "A sticking point for me is keeping up to up date with all the newest libraries and frameworks that are always revolving, and just staying constant on practicing for both ends of the stack. My first jump back into javascript from python after 2 weeks without curly brackets, It was a struggle to say the least to remember the right syntax.",
        third: "Connecting the front end to the back was a more simple process then what I thought. I was not aware that APIs were able to take requests from the front end and modify the database, because I have only ever used APIs to read data from. I figured there'd be a whole separate process to send data back until I realized that Axios had methods named after all the CRUD functions.",
        id: 9,
    },
    {
        header: "Finish Line",
        date: "4-14-23",
        img: "../img/agile.png",
        imgAlt: "Agile Cycle",
        first: "Agile development is an approach towards software development, focused more around the customer, than around the initial plans. Agile is named aptly since the whole process it covers is agile in the way that if the plans change no matter the reason, the development should be able to pivot without nuking and paving the entire project and starting from the ground. Agile methodologies also include communication and collaboration between multiple teams who are working on separate aspects of the project. This week we solely focused on our MVPs, and besides me updating my portfolio with new stuff I've learned, there was no coding this week. Definitely was a different week that was slow to start, but it highlights an importance aspect of agile development, the MVP is the a way to obtain the most data for the project with the least effort while providing something for the customer.",
        second: "Frameworks are beneficial because they reduce the amount of code you need to write and in doing so also keep with DRY principles. Theres no need to reinvent the wheel, and sometimes someone has already wrote a thousand plus lines of code and even made classes, methods, and functions to make it easier for you to implement the code into your project without interfering with anything already in it.",
        third: "",
        id: 10,
    },
    {
        header: "Final Project 1",
        date: "a",
        img: "a",
        imgAlt: "a",
        first: "a",
        second: "a",
        third: "a",
        id: 11,
    },
    {
        header: "Final Project 2",
        date: "a",
        img: "a",
        imgAlt: "a",
        first: "a",
        second: "a",
        third: "a",
        id: 12,
    },
    {
        header: "What Now?",
        date: "a",
        img: "a",
        imgAlt: "a",
        first: "a",
        second: "a",
        third: "a",
        id: 13,
    }
];